name: ding
email: ding@gmail.com
#??????
content: "name: ${name}, email: ${email}"


#????? studentProperties
student:
  name: zhong
  email: zhong@gmail.com


server:
  port: 8080
#  context-path: /kyee


#mvn install
#java -jar *.jar --spring.profiles.active=prod
spring:
  thymeleaf:
    encoding: UTF-8
    cache: false
    mode: HTML5

  profiles:
    active: dev
#  data:
#    mongodb: #MONGODB
#      host: localhost
#      port: 27017
#      database: test

