server:
  port: 8012
spring:
  application:
    name: ms-exam
eureka:
  client:
    serviceUrl:
#      defaultZone: http://discovery:8761/eureka/    # 指定注册中心的地址
      defaultZone: http://127.0.0.1:8761/eureka/    # 指定注册中心的地址
    instance:
      perferIpAddress: true