server:
  port: 8012
spring:
  redis: # REDIS (RedisProperties)
      database: 5 # Redis数据库索引（默认为0）
      host: localhost # Redis服务器地址
      port: 6379 # Redis服务器连接端口
      password: # Redis服务器连接密码（默认为空）
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
      timeout: 0 # 连接超时时间（毫秒）

  application:
    name: ms-exam
eureka:
  client:
    serviceUrl:
#      defaultZone: http://discovery:8761/eureka/    # 指定注册中心的地址
      defaultZone: http://127.0.0.1:8761/eureka/    # 指定注册中心的地址
    instance:
      perferIpAddress: true
