server:
  port: 8030
spring:
  application:
    name: ms-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wangshikeyi/spring-boot-init/     # 配置git仓库的地址
          search-paths: config-repo                                 # git仓库地址下的相对地址，可以配置多个，用,分割
          username:                                                 # git仓库的账号
          password:                                                 # git仓库的密码

    ### spring cloud config server 中加入spring cloud bus 实现config的自动刷新
    bus:
      trace:
        enabled: true        #开启cloud bus 跟踪
  rabbitmq:
    host: localhost
    port: 5672
    username: springcloud
    password: 123456

eureka:
  client:
    serverUrl:
#      defaultZone: http://discovery:8761/eureka/    # 指定注册中心的地址
      defaultZone: http://127.0.0.1:8761/eureka/    # 指定注册中心的地址